### PR TITLE
Fixed gradle build and added gradle wrapper for reproducible builds

### PR DESCRIPTION
**Pull request by breucode**

### CODE REVIEW

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
Tho did almost the same myself

**Comment by 1-alex98** [comment]
So maybe I just merge mine

**Comment by n3roxis** [comment]
Axel you are saying that I should merge #30 Spawn number instead? If yes, I'll do so and remove this.

**Comment by 1-alex98** [comment]
Well no let's merge this

**Review by 1-alex98 — APPROVED** [review]

**Comment by 1-alex98** [comment]
take my PR

**Pull request merged**
