### PR TITLE
Tweaked Biomes

### PR DESCRIPTION
**Pull request by Penguin5**
Adjusted biomes: Desert, Frithen, Loki, Mars, Moonlight, Prayer, Stones, and Syrtis
Changes were primarily to water settings and lighting

### CODE REVIEW

**Comment by Sheikah45** [comment]
Need pictures of before and after. Although if the changes are purely personal opinion there is no guarantee on them getting merged as otherwise this just turns into a back and forth of prs which I do not want.

**Comment by Penguin5** [comment]
Images posted in order of old then new:
Mars
image
image
Frithen
image
image
Loki
image
image
Desert
image
image
Moonlight
image
image
Syrtis
image
image
Prayer
image
image
Stones
image
image

**Comment by Sheikah45** [comment]
This looks like it is just reverting the color changes that blackyps made. I think this only reduces the variance of the biomes so will not be merged.

**Comment by Penguin5** [comment]
I spent time manually adjusting each of those.  I didn't revert it to an old version.  I'd like the changes to actually be considered rather than just unilaterally swept aside.  I can understand not merging some of the changes and or suggesting further adjustments to them, but I think unilaterally rejecting all of them is the wrong way to handle this situation.

**Comment by Sheikah45** [comment]
All this appears to have done is set the colors to all be the same blue. The purpose of changing the water was to give it more variety. This pr removes the variety and that seems to be your intent. So there are no comments beyond it is not in the spirit of where I think these biomes should be.

**Pull request closed without merging**
