### PR TITLE
Biome doc

### PR DESCRIPTION
**Pull request by Rackover**

### CODE REVIEW

**Comment by 1-alex98** [comment]
I say let's just take it even if unfinished. better than no docs

**Comment by Rackover** [comment]
Please at least add the screenshots for the missing biomes, and remove/update the sections of the readme that are unfinished :)

**Comment by 1-alex98** [comment]
If I knew how to XD I would just write TODO in the empty sections

**Comment by n3roxis** [comment]
I'm going through all pull requests since stuff is happening.
Could this one be merged?
Currently it is still marked as in progress

**Comment by 1-alex98** [comment]
I'd say just merge it...

**Pull request closed without merging**
